repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: name-tests-test
        args: [--pytest-test-first]

  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.7.2
    hooks:
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.8
    hooks:
      # Run the linter with import sorting and unused import removal
      - id: ruff
        args: [
          --fix,
          --select=I,F401,  # I for import sorting, F401 for unused imports
          #--fix-only,       # Only fix, don't report remaining issues
        ]
      # Run the complete linter after fixes
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
